### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by Bill-Haoyu-Lin** [macrobomaster/cv-yolov7#32]
## Description
Tracking for auto-aim, auto-crate-takeout&deposit and movement correction. 
- [ ] auto-aim
- [ ] #37 -- side quest

## related issues 
#5 better model
#9 C/C++ code transfer(if needed)
#8 Target and number classify
#15 tracking

### auto-aim
We need to deploy better object detection and tracking 

- [ ] obejct detection (current progress 20ms per image)
- [ ] object tracking --- so it won't lose target
- [ ] movement prediction --- compensate delay
- [ ] depth estimation

### auto-crate-deposit&takeout-- side quest
we need to have algorithm to allow CV board set command to control engineer robot to takeout ammo-crate and deposit it to exchange station at base. 

- [ ] auto-takeout recognition for location and angle
- [ ] auto-deposit recognition for location and angle

![image](https://github.com/macrobomaster/cv-yolov7/assets/56321690/97326d2c-60d9-48f5-ba05-950be8258336)

**Comment by juliandevv** [comment]
We don't need the auto crate deposit since the engineer robot is allowed regular control when in the exchange station.

**Comment by Bill-Haoyu-Lin** [comment]
> We don't need the auto crate deposit since the engineer robot is allowed regular control when in the exchange station.

Yes Julian, we will keep it as a side quest lol.
