### ISSUE TITLE
Customized Protocol 

### ISSUE THREAD

**Issue by Bill-Haoyu-Lin** [macrobomaster/cv-yolov7#34]
## Description 
In order to communicate and passing command to control board, we need to establish certain kind of way to communicate in both-way. Currently we are using UART to communicate. But we will need to transfer to I2C or other one for better performance

### Tasks

- [ ] Familier with UART, I2C, etc, find the best fit for our case
- [ ] get to know how to write protocal
- [ ] Communicate with CV team and Control Team for what kind of data need to be passed around
- [ ] setup connection

## Useful Links
https://www.totalphase.com/blog/2021/12/i2c-vs-spi-vs-uart-introduction-and-comparison-similarities-differences/
