### ISSUE TITLE
ROS Investigation

### ISSUE THREAD

**Issue by Bill-Haoyu-Lin** [macrobomaster/cv-yolov7#35]
## Description

ROS acts like a framework for our purpose. We will use it to connect all parts together. 

### Tasks

- [ ] Know how to create nodes and public and subscribe information
- [ ] Know how to create multiple nodes and make them work together
- [ ] evaluate the performance and improve
